# Generated by Django 5.2.1 on 2026-01-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_articlesnapshot_is_moderated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='is_moderated',
        ),
        migrations.AddField(
            model_name='articlesnapshot',
            name='moderation_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Withdrawn'), (3, 'Approved'), (4, 'Rejected')], db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['moderation_status', 'created_at'], name='articles_ar_moderat_f773c4_idx'),
        ),
    ]
