# Generated by Django 5.2.1 on 2025-08-10 11:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_avatar_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=users.models.AvatarStorage(), upload_to='avatars/'),
        ),
    ]
