# Generated by Django 5.2.1 on 2025-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
