# Generated by Django 5.2.1 on 2025-12-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
