# Generated by Django 5.2.1 on 2026-01-08 09:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=users.models.AvatarStorage(), upload_to=users.models.avatar_upload_to),
        ),
    ]
